project                  = "cwb03-dev-a1fe"
project_prefix           = "cwb03"
region                   = "us-east4"
environment              = "dev"
user_management_base_url = "https://api-dev.cwb03.dsgov.demo.nuvalence.io/um"
